en:
  languageName: English
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: "Copyright &copy; {{< current_year >}} Cosent BV. Website based on [Dot Org Theme](https://github.com/cncf/dot-org-hugo-theme) for Hugo by [CNCF](https://www.cncf.io)."
  title: "Cosent"
  params:
    description: "Site Description in languages.yaml"
    ### accessibility ###
    accessibility:
      skip_text: "Skip to content"
      help_text: "Accessibility Statement"
      help_url: "/example-page/"
    ### calls to action ###
    main_cta:
      text: "Contact"
      link: "/example-page/"
    footer_cta:
      # text: "Join us"
      # link: "/example-page/"
    github_edit: "Edit this page on GitHub"
  ### example menu showing children ###
  menu:
    main:
    - identifier: "services"
      name: "Services"
      url: "/demo-page/"
      weight: 1
    - identifier: "blog"
      name: "Blog"
      url: "/blog/"
      weight: 2
    - identifier: "about"
      name: "About"
      url: "/example-page/"
      weight: 4
    - identifier: "child-1"
      name: "Company"
      url: "/example-page/"
      weight: 2
      post: "Aenean commodo ligula get dolor. Aenean massa."
      parent: "about"
    - identifier: "child-2"
      name: "Presentations"
      url: "/example-page/"
      weight: 2
      post: "Aenean commodo ligula get dolor. Aenean massa."
      parent: "about"
    - identifier: "child-3"
      name: "Publications"
      url: "https://cncf.io?ref=dot-org"
      weight: 3
      post: "Lorem ipsum dolor sit amet consectetuer adipiscing elit aenean commodo."
      parent: "about"
    - identifier: "quaive"
      name: "Quaive"
      url: "https://quaive.com"
      weight: 5

nl:
  languageName: Nederlands
  contentDir: content/nl
  weight: 2
  title: "Cosent"
  params:
    description: "Hier komt een beschrijving"
  menu:
    main:
    - identifier: "about"
      name: "Over"
      url: "/example-page/"
      weight: 1
    - identifier: "child-1"
      name: "Voorbeeld"
      url: "/example-page/"
      weight: 1
      parent: "about"
    - identifier: "faq"
      name: "FAQs"
      url: "/faq/"
      weight: 3
    - identifier: "blog"
      name: "Blog"
      url: "/blog/"
      weight: 2
