[build.environment]
DART_SASS_VERSION = "1.89.2"
GO_VERSION = "1.24.2"
HUGO_VERSION = "0.148.0"
NODE_VERSION = "22"
TZ = "America/Los_Angeles"

[build]
publish = "public"
command = """\
  curl -LJO https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
  tar -xf dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
  rm dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
  export PATH=/opt/build/repo/dart-sass:$PATH && \
  git config core.quotepath false && \
  hugo --gc --minify && \
  npm_config_yes=true npx pagefind --site 'public' --output-subdir 'pagefind'
  """

[[redirects]]
    from = "/en/blog/future-knowledge-work.html"
    to = "/blog/future-knowledge-work"
[[redirects]]
    from = "/blog/digital-workplace-technology-roadmap"
    to = "/blog/future-knowledge-work"

[[redirects]]
    from = "/en/blog/high-availability-high-performance-plone.html"
    to = "/blog/high-availability-high-performance-plone"
[[redirects]]
    from = "/blog/high-availability-high-performance-ploneconf2013"
    to = "/blog/high-availability-high-performance-plone"

[[redirects]]
    from = "/en/blog/plone-software-ecology.html"
    to = "/blog/plone-software-ecology"
[[redirects]]
    from = "/blog/corporatizing-open-source-innovation-plone"
    to = "/blog/plone-software-ecology"

[[redirects]]
    from = "/en/blog/plonesocial-ploneconf2013.html"
    to = "/blog/plonesocial-ploneconf2013"
[[redirects]]
    from = "/blog/plonesocial-roadmap-ploneconf2013"
    to = "/blog/plonesocial-ploneconf2013"
